services:
  postgres:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go:
    build: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./main:/app
    tty: true



volumes:
  pgdata:
