services:
  postgres:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go:
    build: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    tty: true

  react:
    build: ./react
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    tty: true

volumes:
  pgdata:
